### ISSUE TITLE
the errors in the code

### ISSUE THREAD

**Issue by jzhou3700** [hengruizhang98/GCMC-Pytorch-dgl#3]
Traceback (most recent call last):
  File "D:/Z.J/gitfile/GCMC-Pytorch-dgl/main.py", line 63, in <module>
    predictions = model(u_feat, i_feat, enc_G, train_dec_G)
  File "C:\Users\zhoujie\.conda\envs\HGT\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Z.J\gitfile\GCMC-Pytorch-dgl\model.py", line 41, in forward
    u_feat, i_feat = self.feat_tran(u_feat, i_feat)
  File "C:\Users\zhoujie\.conda\envs\HGT\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Z.J\gitfile\GCMC-Pytorch-dgl\model.py", line 73, in forward
    trans_u_feat = self.u_dense(u_feat)
  File "C:\Users\zhoujie\.conda\envs\HGT\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Z.J\gitfile\GCMC-Pytorch-dgl\model.py", line 97, in forward
    in_feat = layer(in_feat)
  File "C:\Users\zhoujie\.conda\envs\HGT\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\zhoujie\.conda\envs\HGT\lib\site-packages\torch\nn\modules\linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\zhoujie\.conda\envs\HGT\lib\site-packages\torch\nn\functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument mat1 in method wrapper_addmm)

**Comment by hengruizhang98** [comment]
This repo is out-of-date, please try the official implementation: DGL official implementation: https://github.com/dmlc/dgl/tree/master/examples/pytorch/gcmc.
